using System.Xml.Serialization;
using Dalamud.Game.ClientState.Conditions;

namespace MacroMate.Serialization.V1;

/// <summary>
/// Stable XML serialization mirror of <see cref="ConditionFlag"/>.
/// Decouples serialized XML from upstream enum renames.
/// Uses exhaustive switch mappings so upstream changes cause compile errors.
/// </summary>
public enum ConditionFlagXML {
    None = ConditionFlag.None,
    NormalConditions = ConditionFlag.NormalConditions,
    Unconscious = ConditionFlag.Unconscious,
    Emoting = ConditionFlag.Emoting,
    Mounted = ConditionFlag.Mounted,
    Crafting = ConditionFlag.Crafting,
    Gathering = ConditionFlag.Gathering,
    MeldingMateria = ConditionFlag.MeldingMateria,
    OperatingSiegeMachine = ConditionFlag.OperatingSiegeMachine,
    CarryingObject = ConditionFlag.CarryingObject,
    RidingPillion = ConditionFlag.RidingPillion,
    Mounted2 = ConditionFlag.RidingPillion,
    InThatPosition = ConditionFlag.InThatPosition,
    ChocoboRacing = ConditionFlag.ChocoboRacing,
    PlayingMiniGame = ConditionFlag.PlayingMiniGame,
    PlayingLordOfVerminion = ConditionFlag.PlayingLordOfVerminion,
    ParticipatingInCustomMatch = ConditionFlag.ParticipatingInCustomMatch,
    Performing = ConditionFlag.Performing,
    Occupied = ConditionFlag.Occupied,
    InCombat = ConditionFlag.InCombat,
    Casting = ConditionFlag.Casting,
    SufferingStatusAffliction = ConditionFlag.SufferingStatusAffliction,
    SufferingStatusAffliction2 = ConditionFlag.SufferingStatusAffliction2,
    Occupied30 = ConditionFlag.Occupied30,
    OccupiedInEvent = ConditionFlag.OccupiedInEvent,
    OccupiedInQuestEvent = ConditionFlag.OccupiedInQuestEvent,
    Occupied33 = ConditionFlag.Occupied33,
    BoundByDuty = ConditionFlag.BoundByDuty,
    OccupiedInCutSceneEvent = ConditionFlag.OccupiedInCutSceneEvent,
    InDuelingArea = ConditionFlag.InDuelingArea,
    TradeOpen = ConditionFlag.TradeOpen,
    Occupied38 = ConditionFlag.Occupied38,
    Occupied39 = ConditionFlag.Occupied39,
    ExecutingCraftingAction = ConditionFlag.ExecutingCraftingAction,
    PreparingToCraft = ConditionFlag.PreparingToCraft,
    ExecutingGatheringAction = ConditionFlag.ExecutingGatheringAction,
    Fishing = ConditionFlag.Fishing,
    BetweenAreas = ConditionFlag.BetweenAreas,
    Stealthed = ConditionFlag.Stealthed,
    Jumping = ConditionFlag.Jumping,
    UsingChocoboTaxi = ConditionFlag.UsingChocoboTaxi,
    OccupiedSummoningBell = ConditionFlag.OccupiedSummoningBell,
    BetweenAreas51 = ConditionFlag.BetweenAreas51,
    SystemError = ConditionFlag.SystemError,
    LoggingOut = ConditionFlag.LoggingOut,
    ConditionLocation = ConditionFlag.ConditionLocation,
    WaitingForDuty = ConditionFlag.WaitingForDuty,
    BoundByDuty56 = ConditionFlag.BoundByDuty56,
    MountOrOrnamentTransition = ConditionFlag.MountOrOrnamentTransition,
    WatchingCutscene = ConditionFlag.WatchingCutscene,
    WaitingForDutyFinder = ConditionFlag.WaitingForDutyFinder,
    CreatingCharacter = ConditionFlag.CreatingCharacter,
    Jumping61 = ConditionFlag.Jumping61,
    PvPDisplayActive = ConditionFlag.PvPDisplayActive,
    SufferingStatusAffliction63 = ConditionFlag.SufferingStatusAffliction63,
    Mounting = ConditionFlag.Mounting,
    CarryingItem = ConditionFlag.CarryingItem,
    UsingPartyFinder = ConditionFlag.UsingPartyFinder,
    UsingHousingFunctions = ConditionFlag.UsingHousingFunctions,
    Transformed = ConditionFlag.Transformed,
    OnFreeTrial = ConditionFlag.OnFreeTrial,
    BeingMoved = ConditionFlag.BeingMoved,
    Mounting71 = ConditionFlag.Mounting71,
    SufferingStatusAffliction72 = ConditionFlag.SufferingStatusAffliction72,
    SufferingStatusAffliction73 = ConditionFlag.SufferingStatusAffliction73,
    RegisteringForRaceOrMatch = ConditionFlag.RegisteringForRaceOrMatch,
    WaitingForRaceOrMatch = ConditionFlag.WaitingForRaceOrMatch,
    WaitingForTripleTriadMatch = ConditionFlag.WaitingForTripleTriadMatch,
    InFlight = ConditionFlag.InFlight,
    WatchingCutscene78 = ConditionFlag.WatchingCutscene78,
    InDeepDungeon = ConditionFlag.InDeepDungeon,
    Swimming = ConditionFlag.Swimming,
    Diving = ConditionFlag.Diving,
    RegisteringForTripleTriadMatch = ConditionFlag.RegisteringForTripleTriadMatch,
    WaitingForTripleTriadMatch83 = ConditionFlag.WaitingForTripleTriadMatch83,
    ParticipatingInCrossWorldPartyOrAlliance = ConditionFlag.ParticipatingInCrossWorldPartyOrAlliance,
    Unknown85 = ConditionFlag.Unknown85,
    DutyRecorderPlayback = ConditionFlag.DutyRecorderPlayback,
    Casting87 = ConditionFlag.Casting87,
    MountImmobile = ConditionFlag.MountImmobile,
    InThisState88 = ConditionFlag.MountImmobile,
    InThisState89 = ConditionFlag.InThisState89,
    RolePlaying = ConditionFlag.RolePlaying,
    InDutyQueue = ConditionFlag.InDutyQueue,
    ReadyingVisitOtherWorld = ConditionFlag.ReadyingVisitOtherWorld,
    WaitingToVisitOtherWorld = ConditionFlag.WaitingToVisitOtherWorld,
    UsingFashionAccessory = ConditionFlag.UsingFashionAccessory,
    BoundByDuty95 = ConditionFlag.BoundByDuty95,
    Unknown96 = ConditionFlag.Unknown96,
    Disguised = ConditionFlag.Disguised,
    RecruitingWorldOnly = ConditionFlag.RecruitingWorldOnly,
    Unknown99 = ConditionFlag.Unknown99,
    EditingPortrait = ConditionFlag.EditingPortrait,
    Unknown101 = ConditionFlag.Unknown101,
    PilotingMech = ConditionFlag.PilotingMech,
    EditingStrategyBoard = ConditionFlag.EditingStrategyBoard
}

public static class ConditionFlagXMLExtensions {
    public static ConditionFlagXML ToXml(this ConditionFlag value) => (ConditionFlagXML)value;
    public static ConditionFlag FromXml(this ConditionFlagXML value) => (ConditionFlag)value;
}
